### ISSUE TITLE
Assertion In Storage

### ISSUE THREAD

**Issue by thanhduc2000** [AY1920S2-CS2113T-T13-3/tp#70]
For assertion in storage, it is assumed that there must be a number of certain fields to be inputted. However, for clear commands, since it doesn't need to input any fields so changes in the assumptions in Storage class are needed.

**Comment by brandoncjh** [comment]
Do you mean the assertions in Storage are preventing the clear command from running? I can remove them if that's what you are asking.

**Comment by thanhduc2000** [comment]
Yeah and I just commented them out, but you can figure out a way to implement a new assertion if you want.
